### ISSUE TITLE
An optional attribute of a class should be set as null if not defined in the json object

### ISSUE THREAD

**Issue by jjaferson** [dpopescu/ts-serializer#10]
If a class has an optional attribute and it is not defined in the Json object it throws an error instead of set the attribute as null  

**Plain Json**
`user = {
id: 1,
name: "David"
}`

**// Type script classes**

class User  extends Serializable {
@SerializeProperty({})
public id: number,
@SerializeProperty({})
public name: string,
    @SerializeProperty({
        list: true,
        type: Address
    })
addresses?: Array<Address>
}

class Address  extends Serializable  {
    @SerializeProperty({})
street: string,
    @SerializeProperty({})
city: string,
    @SerializeProperty({})
country: string
}`

**Comment by hassanrazakhalid** [comment]
I am facing the same issues... how can we allow it to skip the properties which don't exist in the json

**Comment by dpopescu** [comment]
I will try to detect if a property is marked as optional using reflection. If not, the only way is to add another property to the `options` object. Something like  `optional:true|false`. I don't like this approach because you have to mark the property as optional in 2 different ways. If you guys have any other ideas please submit a PR :)

**Comment by delete** [comment]
I'm closing this issue because we now have the option to mark a property as `optional`.

You can reopen, if you need to.

https://github.com/dpopescu/ts-serializer#optional
